### PR TITLE
Modernize a few things

### PR DESCRIPTION
**Pull request by Adafede**
Hi @EBjerrum, @JanoschMenke,

First, thank you so much for this tool!

Because when I tried to install and run it many old dependencies could not be found, I made a very humble attempt to modernize a few things:

- [x] Switching from `setup.py` to `pyproject.toml` (allows installation using `pdm`, `poetry`, and consorts).
- [ ] Switching from `PySide2`to `PySide6`.
    - [ ] I had to disable some buttons/shortcuts I was not able to fully port to `PySide6`. All the parts are commented by `## TODO (AR): I could not getting this to work with PySide6`  

I believe these are easily fixable, but error messages were not very informative, except `PySide6`seems more stringent regarding the classes.
    
I hope this helps some ways.

### CODE REVIEW

**Comment by EBjerrum** [comment]
I'm sorry to hear you had issues with the current installer. It is tested on my and my collaborators setups and work fine there, even though pyside2 is a burning platform. 

Thanks for the effort with the pull request, but you should have reached out before you made the effort. I already have an internal branch with a port for PySide6, but that switch has to be delayed a bit, due to some downstream dependants that must be fixed first. Are you interested in helping out more with the project?

Esben Jannik Bjerrum
cand.pharm, Ph.D
Phone +46 76 303 90 13 
http://dk.linkedin.com/in/esbenbjerrum
https://www.cheminformania.com

 

    On Friday, May 3, 2024 at 09:56:05 AM GMT+2, Adriano Rutz ***@***.***> wrote:  
 
 
Hi @EBjerrum,

First, thank you so much for this tool!

Because when I tried to install and run it many old dependencies could not be found, I made a very humble attempt to modernize a few things:
   
   -  Switching from setup.py to pyproject.toml (allows installation using pdm, poetry, and consorts).
   -  Switching from PySide2to PySide6.      
      -  I had to disable some buttons/shortcuts I was not able to fully port to PySide6. I believe these are easily fixable, but error messages were not very informative, except PySide6seems more stringent regarding the classes.


I hope this helps some ways.

You can view, comment on, or merge this pull request online at:

  https://github.com/EBjerrum/rdeditor/pull/16

Commit Summary
   
   - 0fb99f5 modernizing a few things

File Changes 
 
(10 files)
   
   -  M CITATION.bib (2) 
   -  M README.md (6) 
   -  A pyproject.toml (27) 
   -  M rdeditor/molEditWidget.py (2) 
   -  M rdeditor/molViewWidget.py (4) 
   -  M rdeditor/ptable_widget.py (28) 
   -  M rdeditor/rdEditor.py (171) 
   -  D setup.py (40) 
   -  A src/rdeditor/__init__.py (0) 
   -  A tests/__init__.py (0) 

Patch Links:
   
   - https://github.com/EBjerrum/rdeditor/pull/16.patch
   - https://github.com/EBjerrum/rdeditor/pull/16.diff

**Comment by Adafede** [comment]
No worries, as stated in the PR I did not make the effort of fixing things deeply so it wasn't that much effort. 😊

I would love to see the project grow, and support for example CX SMILES/SMARTS.
Maybe I can help on a few things, probably not much.

Anyway, feel free to cherry pick parts that might be helpful to you, be it the `pyproject.toml` or else!

**Comment by EBjerrum** [comment]
Fixed with merge #21

**Comment by Adafede** [comment]
👍🏼

**Pull request closed without merging**
